[project]
name = "cut-swift-rev-crack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "peft>=0.21.2",
    "vllm>=0.31.0",
]

[project.scripts]
cut-swift-rev-crack = "cut_swift_rev_crack:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
